-- ============================================================
-- SLUZBA
-- ============================================================
CREATE TABLE impl.sluzba
(
    sluzba_id   BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    naziv       VARCHAR(22)                                NOT NULL,

    CONSTRAINT pk_sluzba        PRIMARY KEY (sluzba_id),
    CONSTRAINT uq_sluzba_naziv  UNIQUE (naziv)
);

-- ============================================================
-- RADNO_MESTO
-- ============================================================
CREATE TABLE impl.radno_mesto
(
    radno_mesto_id   BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    naziv            VARCHAR(22)                                NOT NULL,

    CONSTRAINT pk_radno_mesto        PRIMARY KEY (radno_mesto_id),
    CONSTRAINT uq_radno_mesto_naziv  UNIQUE (naziv),
    CONSTRAINT chk_radno_mesto_naziv CHECK (naziv ~ '^[A-ZČĆŽŠĐ]')
);

-- ============================================================
-- PROJEKAT
-- ============================================================
-- Napomena: klasa se postavlja automatski putem BEFORE trigera
-- (fn_auto_klasifikacija) na osnovu vrednosti budžeta.
CREATE TABLE impl.projekat
(
    projekat_id  BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    naziv        VARCHAR(50)                                NOT NULL,
    budzet       NUMERIC(15,2)                              NOT NULL,
    klasa        SMALLINT                                   NOT NULL,

    CONSTRAINT pk_projekat         PRIMARY KEY (projekat_id),
    CONSTRAINT uq_projekat_naziv   UNIQUE (naziv),
    CONSTRAINT chk_projekat_naziv  CHECK (naziv LIKE 'PR-%'),
    CONSTRAINT chk_projekat_budzet CHECK (budzet > 0),
    CONSTRAINT chk_projekat_klasa  CHECK (klasa IN (1, 2, 3))
);

-- ============================================================
-- RADNIK
-- ============================================================
CREATE TABLE impl.radnik
(
    radnik_id      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 2)  NOT NULL,
    ime            VARCHAR(22)                                                               NOT NULL,
    sluzba_id      BIGINT                                                                   NOT NULL,
    radno_mesto_id BIGINT                                                                   NOT NULL,

    CONSTRAINT pk_radnik              PRIMARY KEY (radnik_id),
    CONSTRAINT chk_radnik_ime         CHECK (ime ~ '^[A-ZČĆŽŠĐ]'),
    CONSTRAINT fk_radnik_sluzba       FOREIGN KEY (sluzba_id)      REFERENCES impl.sluzba(sluzba_id),
    CONSTRAINT fk_radnik_radno_mesto  FOREIGN KEY (radno_mesto_id)  REFERENCES impl.radno_mesto(radno_mesto_id)
);

-- ============================================================
-- ISPLATA (slab entitet — zavisi od Radnika)
-- ============================================================
CREATE TABLE impl.isplata
(
    radnik_id    BIGINT                                       NOT NULL,
    isplata_id   BIGINT GENERATED BY DEFAULT AS IDENTITY      NOT NULL,
    datum        DATE                                          NOT NULL,
    iznos        NUMERIC(15,2)                                 NOT NULL,
    vrsta        VARCHAR(11)                                   NOT NULL,

    CONSTRAINT pk_isplata         PRIMARY KEY (radnik_id, isplata_id),
    CONSTRAINT chk_isplata_iznos  CHECK (iznos > 0),
    CONSTRAINT chk_isplata_vrsta  CHECK (vrsta IN ('PLATA', 'BONUS', 'REGRES')),
    CONSTRAINT fk_isplata_radnik  FOREIGN KEY (radnik_id) REFERENCES impl.radnik(radnik_id) ON DELETE CASCADE
);

-- ============================================================
-- UCESTVUJE (agregacija — Radnik ↔ Projekat)
-- ============================================================
CREATE TABLE impl.ucestvuje
(
    ucestvuje_id  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    datum_od      DATE                                                                      NOT NULL,
    datum_do      DATE                                                                      NULL,
    radnik_id     BIGINT                                                                    NOT NULL,
    projekat_id   BIGINT                                                                    NOT NULL,

    CONSTRAINT pk_ucestvuje            PRIMARY KEY (ucestvuje_id),
    CONSTRAINT chk_ucestvuje_trajanje  CHECK (datum_do IS NULL OR (datum_do - datum_od) >= 15),
    CONSTRAINT fk_ucestvuje_radnik     FOREIGN KEY (radnik_id)   REFERENCES impl.radnik(radnik_id),
    CONSTRAINT fk_ucestvuje_projekat   FOREIGN KEY (projekat_id) REFERENCES impl.projekat(projekat_id)
);

-- ============================================================
-- RUKOVODI (agregacija — Radnik → Projekat, 1:1 po projektu)
-- ============================================================
CREATE TABLE impl.rukovodi
(
    rukovodi_id   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    radnik_id     BIGINT                                                                   NOT NULL,
    projekat_id   BIGINT                                                                   NOT NULL,

    CONSTRAINT pk_rukovodi           PRIMARY KEY (rukovodi_id),
    CONSTRAINT uq_rukovodi_projekat  UNIQUE (projekat_id),
    CONSTRAINT fk_rukovodi_radnik    FOREIGN KEY (radnik_id)   REFERENCES impl.radnik(radnik_id),
    CONSTRAINT fk_rukovodi_projekat  FOREIGN KEY (projekat_id) REFERENCES impl.projekat(projekat_id) ON DELETE CASCADE
);
