-- ============================================================
-- ZVANJE
-- ============================================================
CREATE TABLE impl.zvanje
(
    id_zvanje   INT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    naziv       VARCHAR(35)                             NOT NULL,

    CONSTRAINT pk_zvanje        PRIMARY KEY (id_zvanje),
    CONSTRAINT uq_zvanje_naziv  UNIQUE (naziv),
    CONSTRAINT chk_zvanje_naziv CHECK (naziv IN ('Docent', 'Vanr. prof.', 'Red. prof.'))
);

-- ============================================================
-- PREDMET
-- ============================================================
CREATE TABLE impl.predmet
(
    id_predmet  INT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    naziv       VARCHAR(35)                             NOT NULL,
    espb        SMALLINT                                NULL        DEFAULT 4,

    CONSTRAINT pk_predmet        PRIMARY KEY (id_predmet),
    CONSTRAINT chk_predmet_espb  CHECK (espb > 2),
    CONSTRAINT chk_predmet_naziv CHECK (naziv ~ '^[A-ZČĆŽŠĐ]')
);

-- ============================================================
-- STUDENT
-- ============================================================
-- Napomena: PostgreSQL ne podržava virtuelne computed kolone.
-- Kolona "starost" se izračunava putem pogleda (VIEW) impl.v_student.
CREATE TABLE impl.student
(
    broj_indeksa    VARCHAR(7)      NOT NULL,
    ime             VARCHAR(22)     NOT NULL,
    datum_rodjenja  DATE            NOT NULL,
    semestar        VARCHAR(4)      NULL        DEFAULT 'I',
    prosecna_ocena  DECIMAL(4,2)    NULL        DEFAULT 0,

    CONSTRAINT pk_student                PRIMARY KEY (broj_indeksa),
    CONSTRAINT chk_student_format_indeksa CHECK (broj_indeksa ~ '^[0-9]{2}/[0-9]{4}$'),
    CONSTRAINT chk_student_ime           CHECK (ime ~ '^[A-ZČĆŽŠĐ]'),
    CONSTRAINT chk_student_semestar      CHECK (semestar IN ('I','II','III','IV','V','VI','VII','VIII'))
);

-- POGLED: v_student — dodaje izvedenu kolonu "starost"
CREATE OR REPLACE VIEW impl.v_student AS
SELECT
    *,
    EXTRACT(YEAR FROM AGE(CURRENT_DATE, datum_rodjenja))::INT AS starost
FROM impl.student;

-- ============================================================
-- NASTAVNIK
-- ============================================================
CREATE TABLE impl.nastavnik
(
    id_nastavnik    INT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    ime             VARCHAR(22)                             NOT NULL,
    id_zvanje       INT                                     NOT NULL,

    CONSTRAINT pk_nastavnik        PRIMARY KEY (id_nastavnik),
    CONSTRAINT fk_nastavnik_zvanje FOREIGN KEY (id_zvanje) REFERENCES impl.zvanje (id_zvanje),
    CONSTRAINT chk_nastavnik_ime   CHECK (ime ~ '^[A-ZČĆŽŠĐ]')
);

-- ============================================================
-- ISPIT
-- ============================================================
CREATE TABLE impl.ispit
(
    id_ispit        INT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    ocena           SMALLINT                                NOT NULL,
    datum_polaganja DATE                                    NOT NULL    DEFAULT CURRENT_DATE,
    broj_indeksa    VARCHAR(7)                              NOT NULL,
    id_predmet      INT                                     NOT NULL,
    id_nastavnik    INT                                     NOT NULL,

    CONSTRAINT pk_ispit                 PRIMARY KEY (id_ispit),
    CONSTRAINT uq_student_predmet       UNIQUE (broj_indeksa, id_predmet),
    CONSTRAINT fk_ispit_student         FOREIGN KEY (broj_indeksa) REFERENCES impl.student (broj_indeksa),
    CONSTRAINT fk_ispit_predmet         FOREIGN KEY (id_predmet)   REFERENCES impl.predmet (id_predmet),
    CONSTRAINT fk_ispit_nastavnik       FOREIGN KEY (id_nastavnik) REFERENCES impl.nastavnik (id_nastavnik),
    CONSTRAINT chk_ispit_ocena          CHECK (ocena >= 6 AND ocena <= 10),
    CONSTRAINT chk_ispit_datum_polaganja CHECK (datum_polaganja <= CURRENT_DATE)
);
